/**
 * Exercise37 - BytecodeDemo
 * 
 * Objective: Explore compiled .class files using the javap disassembler.
 * 
 * This program contains a simple add() method. After compiling, run:
 *     javap -c BytecodeDemo
 * to view the JVM bytecode instructions generated by the compiler.
 * 
 * ─────────────────────────────────────────────
 * KEY JVM BYTECODE INSTRUCTIONS EXPLAINED:
 * ─────────────────────────────────────────────
 * iload_1  → Push local variable slot 1 (int 'a') onto the operand stack.
 * iload_2  → Push local variable slot 2 (int 'b') onto the operand stack.
 * iadd     → Pop top two ints from the stack, add them, push the result.
 * ireturn  → Pop the top int from the stack and return it to the caller.
 * 
 * ldc      → Push a constant (String/int/float) from the constant pool.
 * invokevirtual → Call an instance method (e.g. println).
 * return   → Return void from the current method.
 * ─────────────────────────────────────────────
 */
public class BytecodeDemo {

    /**
     * Adds two integers and returns the result.
     * 
     * Compiled JVM bytecode for this method:
     *   0: iload_1       // Push 'a' onto stack
     *   1: iload_2       // Push 'b' onto stack
     *   2: iadd          // Add and push result
     *   3: ireturn       // Return the result
     */
    public int add(int a, int b) {
        return a + b;
    }

    public static void main(String[] args) {
        BytecodeDemo demo = new BytecodeDemo();
        int result = demo.add(10, 20);

        System.out.println("Compiled Bytecode Listing");
        System.out.println();
        System.out.println("JVM Instructions for add(int a, int b):");
        System.out.println("  iload_1   -> Push 'a' onto operand stack");
        System.out.println("  iload_2   -> Push 'b' onto operand stack");
        System.out.println("  iadd      -> Pop two ints, add, push result");
        System.out.println("  ireturn   -> Return top int from stack");
        System.out.println();
        System.out.println("Result of add(10, 20) = " + result);
        System.out.println();
        System.out.println("Run the following command to view actual bytecode:");
        System.out.println("  javap -c BytecodeDemo");
    }
}
